server:
  port: 8080
#************H2  Begin****************
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username:
    password:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      settings:
        web-allow-other: true
        trace: true
      path: /h2-console
      enabled: true
#************H2  End***************
#************mybatis Start***************
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.entity
#************mybatis End***************
